services:
  music-diary-api:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PORT=5000
    restart: unless-stopped
    networks:
      - music-diary-network

  nginx:
    image: nginx:alpine
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - music-diary-api
    restart: unless-stopped
    networks:
      - music-diary-network

networks:
  music-diary-network:
    driver: bridge 