services:
  music-diary-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:5000"
    environment:
      - PORT=5000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 